version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: DT.Api/Dockerfile
    restart: always
    expose:
      - "80"
    ports:
      - "5000:80"
    links:
      - postgres:postgres
      - redis:redis
    environment:
      DEBUG: 'true'

  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: DT.Web/Dockerfile
    ports:
      - "5100:80"
    depends_on:
      - dt.api

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:

