version: '3.4'

services:
  dt.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  dt.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

